### ISSUE TITLE
improve viridis demo

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/ggplotTraining#6]
Not a huge fan of viridis given that yellow isn't very easy to see. I note that in the mpg dataset, it only has years for 1999 and 2008, so it isn't an ideal demonstration.

**Comment by MattFunnell** [comment]
Agreed, and actually in the latest training session the viridis command wasn’t working for most attendees – even just running the example code. I’ve removed the viridis part of the exercise (and from the solution).
I think the overall example at the end here is useful – to see a (albeit fairly contrived) example of a line graph and think about how to control x and y axis breaks, which is something that will commonly need to be changed. Therefore I have left it in, but welcome any thoughts on how to change this. 

Amended in branch oct_18_issues
