### ISSUE TITLE
mention line-break

### ISSUE THREAD

**Issue by Thomas-Hirsch** [moj-analytical-services/ggplotTraining#7]
it's quite common for people to want to add a line break to denote events. This would just be a geom_line where x = whatever. Might be a bit tricky to adapt as our materials don't really cover time-series, but as it's a common feature I think it's worth mentioning

**Comment by MattFunnell** [comment]
Had never even considered this, and agree it's useful. I've added to slide 24 as a random break along the x axis - whilst the scenario isn't perfect, it does illustrate how you can achieve a line break; and also enhances the point raised on this slide about geoms plotting in layers.

Added in branch oct_18_issues.
